application: decoproyecciones
version: 2
runtime: go
api_version: go1

handlers:
- url: /
  static_files: static/dist/index.html
  upload: static/dist/index.html

- url: /static
  static_dir: static/dist

- url: /js
  static_dir: static/dist/js

- url: /css
  static_dir: static/dist/css

- url: /src
  static_dir: static/src

- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- static/node_modules
- static/bower_components
- static/src
- ^(.*/)?.*/assets/.*$
- ^(.*/)?.*/build/.*$
- ^(.*/)?.*/test/.*$
- ^(.*/)?.*/templates/.*$
- ^(.*/)?.*/node_modules/.*$

- ^(assets/.*)
- ^(build/.*)
- ^(test/.*)
- ^(templates/.*)
- ^(node_modules/.*)

