application: decoproyecciones
version: 2
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: static/angular.html
  upload: static/angular.html

- url: /.*
  script: _go_app

